agent_queue: &agent_queue "queue=zinc-frog"
steps:
  - label: Say hello linux
    command:
      - "whoami"
      - "ls /media/sf_share"
      - "uname -r"
      - "date"
    agents:
      - *agent_queue
    plugins:
      - https://github.com/call/virtualbox-buildkite-plugin#v0.1.1:
          vm-name: ubuntu-vanilla
          vm-snapshot: base
          vm-username: myadmin
          vm-password: admin
